home task 4
Alex-lozovoy/lesson4 pull request #1
Opened 2022-02-07 20:01 UTC by Alex-lozovoy

add lesson 1,lesson 2,lesson 3

2022-02-07 20:35 UTC, fo0lman requested changes

2022-02-07 20:35 UTC, fo0lman commented on ht_1/index.html
> +</html>
В конце каждого файла добавить пустую строку
гх ругается
![image](https://user-images.githubusercontent.com/9566996/152867101-01b83704-bb07-4c10-afd5-f2778ea2a4fa.png)

2022-02-07 20:35 UTC, fo0lman commented on ht_3/pages/search.html
> +</html>
Больше не нашел к чему прикопаться))) потому на своё усмотрение ещё что то поправить и сделать отдельным коммитом
т.е.
1й коммит - подобавлять пустые строки
2й что то поправить/добавить

Потом напишу что делать

2022-02-08 13:32 UTC, fo0lman approved these changes
Всё ок! 

теперь 
* main
git fetch
git pull

2022-02-08 13:32 UTC, merged

2022-02-08 13:49 UTC, Alex-lozovoy commented
main
git fetch
git pull

done )))